name: "C++/CMake Format"

on: [push, pull_request]

jobs:
  format:
    name: "clang-format/cmake-format"
    runs-on: ubuntu-22.04
    steps:
    - name: Install dependencies
      run: |
          sudo apt-get update -y
          sudo apt-get -y --no-install-recommends clang-format='14.*' cmake-format='0.6.*'
    # Check all source and header C++ files; ignore files in hidden directories
    - name: Execute clang-format
      run: find . \( -path '*/.*' -prune \) -o \
        \( -type f -a \( -iname '*.cpp' -o -iname '*.h' \) \) \
        -exec clang-format --dry-run --Werror {} +
    # Check all cmake files; ignore files in hidden directories
    - name: Execute cmake-format
      find . \( -path '*/.*' -prune \) -o \
      \( -type f -a -name 'CMakeLists.txt' \) \
      -exec cmake-format --check -- {} +
